### ISSUE TITLE
Search Overlay Offset on Tinkers Tables

### ISSUE THREAD

**Issue by MoreThanHidden** [feldim2425/MoreOverlays#11]
**Issue:** Search Overlay Offset on Tinkers Tables
**Mod Version:** moreoverlays-1.3-mc1.9.4.jar

**Example Image:**
![searchoverlay](https://cloud.githubusercontent.com/assets/1351964/16170264/c62ff450-357f-11e6-9f08-c21bddfe5d65.PNG)

**Comment by feldim2425** [comment]
I think I can fix it, but it will take a bit of time to do it properly.
