### ISSUE TITLE
Yellow X's - Minor Render Gltich

### ISSUE THREAD

**Issue by AlgorithmX2** [feldim2425/MoreOverlays#12]
Disabling the GUI with the Lighting X's overlay on seems to break the world's lighting.

Its minor, but dosn't reproduce without the X's

Screenshots: http://imgur.com/a/sY9YV

**Comment by feldim2425** [comment]
It don't know why the rendering breaks the lighting. If I try to reproduce it nothing happens.

Screenshot: http://imgur.com/a/c5vqq

**Comment by AlgorithmX2** [comment]
Hmm, Ok, I guess it must be interplay with another mod in the pack, it seemed related to the X's since that seemed to cause it, but I guess there are multiple factors.
