### ISSUE TITLE
Crash with news versions of JEI

### ISSUE THREAD

**Issue by jules552** [feldim2425/MoreOverlays#18]
Hey,

My Minecraft client is crashing when I update my version of JEI (JEI version: 341).

My crash report:
http://pastebin.com/CLAg8XRu

Thank you for you work and have a nice day ;)

**Comment by feldim2425** [comment]
Please Update More Overlays. According to the log you are using Version 1.7. But 1.8 as already out. I tried this version with JEI 3.13.2.354 and there is no crash.

**Comment by jules552** [comment]
Okay thank you, I haven't seen there was a new version.

Sorry :/

**Comment by feldim2425** [comment]
No Problem :D
