### ISSUE TITLE
Request: Configurable "safe" light level

### ISSUE THREAD

**Issue by ghost** [feldim2425/MoreOverlays#19]
Some mods, like [Peaceful Surface](https://minecraft.curseforge.com/projects/peacefulsurface), can change the light level in which hostile mobs spawn. I'd like to be able to configure the light level which the overlay considers unsafe. Thank you.

**Comment by feldim2425** [comment]
Code is added. I will upload the new Versions if i'm done with the 1.11.2 stuff
