### ISSUE TITLE
Crash with newest JEI version

### ISSUE THREAD

**Issue by Videonauth** [feldim2425/MoreOverlays#24]
As described in the JEI bugtracker after updating JEI the game crashes with an error mentioning More Overlays: 

Issue Link on JEI Git: https://github.com/mezz/JustEnoughItems/issues/791#issuecomment-291551717
Crash Report: https://pastebin.com/1i1e4WyW

**Comment by Iareawsome** [comment]
I don't know if this will help, but here is my crash log as well:
[http://chopapp.com/#ib2qm6xc](url)

**Comment by feldim2425** [comment]
I already know why the crash appears. I will try to fix this as fast as possible.
It seems like there are some Classes moved in JEI and my code to find the position of the Search Box throws this exception.

**Comment by Iareawsome** [comment]
Just trying to help. I know that sometimes one crash doesn't provide enough (or diverse enough) info. Just trying to make your life easier, so I can keep using your great mod!

**Comment by kreezxil** [comment]
I see that this has been reported, however, it also does not work with build 259 of JEI

https://pastebin.com/enbbv38E
