### ISSUE TITLE
Search in nearby inventories keybind

### ISSUE THREAD

**Issue by davqvist** [feldim2425/MoreOverlays#25]
MC 1.10.2
Forge 2281
MoreOverlays 1.11

Please correct me if I'm wrong, but the press T in JEI to search in nearby inventories is something your mod adds, right? But I can't find a keybind for that. Not sure if there is an option to turn that off, but even if there was, I want to leave it in the pack but just give players to turn that off by deleting the key in the keybinds. So could you please consider adding a keybind for that feature in the controls?

**Comment by feldim2425** [comment]
Nope my mod doesn't add that Keybind.
It can only search in the currently open inventory, and that is not longer a keybind (double click on the search bar).

**Comment by davqvist** [comment]
Sorry, I was desperately trying to find out which mod adds that as I can't find a keybind for that.
Then someone found this: https://github.com/mezz/JustEnoughItems/issues/438
But I guess they were wrong. Any ideas which mod adds that?

**Comment by davqvist** [comment]
Nevermind I found it out, it's ExtraUtilities. Sorry for bothering you.
