### ISSUE TITLE
[1.11-mc1.11.2] jei updated to build 287 now your mod crashes

### ISSUE THREAD

**Issue by kreezxil** [feldim2425/MoreOverlays#27]
client crash report
https://pastebin.com/fhZ1w1Ar

**Comment by drakray** [comment]
jei 287 is 13 hours old, mod update is NOT live...
Still, I got this too, but I wonder, why is MoreOverlay dependent on JEI anyway?
Couldn't it work another way, without dependency?(would reduce these problem)

EDIT: I forgot about the Item Search function(which is the JEI stuff)
