### ISSUE TITLE
Crash when trying to tab autocomplete

### ISSUE THREAD

**Issue by Melakion** [feldim2425/MoreOverlays#3]
Tried to tab autocomplete in a /give command and crashed.

http://pastebin.com/CXHH8wWT

MC 1.9 - Forge 1857 - moreoverlays-0.6-mc1.9

**Comment by feldim2425** [comment]
Is JEI installed? If yes, what version? 
If no, there are 2 bugs:
*) It crash if you try to enable item search without JEI.
*) TAB enables the item search.

**Comment by Melakion** [comment]
Was not installed when I got the crash. Was looking for a different issue and trying each mod I updated individually to see which had caused it and caught this crash instead.

**Comment by Melakion** [comment]
ya, works fine with JEI installed. Crash without JEI.
