### ISSUE TITLE
Crash report: what is cuasing this ?

### ISSUE THREAD

**Issue by Kylebartaous** [feldim2425/MoreOverlays#30]
Mine craft version: 1.11.2

Forge version w/ lite loader mix in's: 13.20.0.2315

I seems to be getting a crash with one of the health and info mods , but i am not sure what is doing it.

[crash-2017-06-14_20.03.10-client.txt](https://github.com/feldim2425/MoreOverlays/files/1076302/crash-2017-06-14_20.03.10-client.txt)

The 3-4 mods i use for info on screen and health are, neat, moreoverlays , torohealth damage indictors , jei , wailla, wawla, hwyla. It seems to happen then im looking at a mob and looking down left or down right if it , it would lag for a sec and crash to launcher. thank for you time if you can help me figure what is doing this.

**Comment by feldim2425** [comment]
This Crash is not caused by MoreOverlays (at least it doesn't show up in the stacktrace).
It looks like Better HUD is responsible for this.
