### ISSUE TITLE
Support for searching for specific enchants on books.

### ISSUE THREAD

**Issue by Deathalizer** [feldim2425/MoreOverlays#35]
Hey me and a few buddies use this on an SMP server and are loving yur mod! But one problem is that one of our members has an enchantment shop where they sell enchantment books. and sadly you cannot search for specific books with specific enchantments like you can in the JEI interface. Is there any plans on adding  the ability to search for books with specific enchants within chests? It would be much appreciated if this feature were to be added!

**Comment by feldim2425** [comment]
Well I consider this as a bug. Because I use the Item Filter from JEI, so I cannot (at least not in a clean way) add any feature to search for enchanted books. But that also meanst that my mod should have that ability if JEI has it.
