### ISSUE TITLE
Your Curse page is down.

### ISSUE THREAD

**Issue by InflamedSebi** [feldim2425/MoreOverlays#36]
This page isn’t working
minecraft.curseforge.com redirected you too many times.

at https://minecraft.curseforge.com/projects/more-overlays

Dunno if this is your  issue or a curse issue. But only happens for  your project.

**Comment by InflamedSebi** [comment]
It's working again. Dunno if you or curse did something.

**Comment by feldim2425** [comment]
I can only edit the page but I don't host it (so probably a problem on Curse) . But it seems like they fixed it before I could message them. But I also had that issue a minute ago.
