### ISSUE TITLE
Yellow item search bar overlay too long

### ISSUE THREAD

**Issue by ghost** [feldim2425/MoreOverlays#40]
![more overlays item search bug](https://user-images.githubusercontent.com/25916106/33469067-c5bc8b2c-d660-11e7-974f-c83a0f4f2a30.png)

**Minecraft version**: 1.12.2
**Forge version**: 12.18.3.2511
**More Overlays version**: 1.11
**Just Enough Items version**: 3.14.7.420

**Comment by feldim2425** [comment]
Tinkers Table? If thats the case it is a duplicate of #22

**Comment by ghost** [comment]
Nope. It happens in any inventory.

**Comment by feldim2425** [comment]
I will close this an  merge it with #22
