### ISSUE TITLE
In Modern Skyblock 2 modpack the search function highlights everything.

### ISSUE THREAD

**Issue by ManIkWeet** [feldim2425/MoreOverlays#41]
![image](https://user-images.githubusercontent.com/4006814/33876652-625b54fe-df26-11e7-9af9-dbbbd0d0dbd1.png)

![image](https://user-images.githubusercontent.com/4006814/33876666-69e87a3a-df26-11e7-81b6-a99c0dd120fb.png)

Minecraft version: 1.12.2
Forge version: 14.23.1.2562
More Overlays version: 1.13-mc1.12.1
Just Enough Items version: 4.8.5.135

**Comment by OrdinatorStouff** [comment]
I have experienced this bug for quite some time in ATM3, maybe a couple months or so but admittedly it wasn't a big enough issue to drive me to make a report beforehand. We just had another user [report it to us](https://github.com/AllTheMods/ATM-3/issues/341) and then I found this report so now I know it affects more than just me

**Comment by Shovinus** [comment]
e188322974cb39e5dbc0a7a0c2fd8d4ca5639fbf fixes

**Comment by feldim2425** [comment]
Fixed by Merging e188322
