### ISSUE TITLE
Chunk Border lines stuck

### ISSUE THREAD

**Issue by Discomanco** [feldim2425/MoreOverlays#43]
I have a current issue where the red lines that marks the borders wont go away.
If I press F9, they become thicker, as there's now 2 red lines on top of each other, and the yellow line appears
If I press F9 again, then chunk border walls come.
If I press F9 again, it's back to just the red lines.

F3+G makes the blue lines purple.

It started a few days ago, and I'm not sure how, or exactly when, but it's starting to be annoying

**Comment by feldim2425** [comment]
This shouldn't happen since there is only one static variable that tells the mod if it should render or not. Is there any other mod installed that renders Chunk Lines? Like NEI or Chunk Edge Indicator?

**Comment by feldim2425** [comment]
Since there is no answer to my question for almost 11 months. I will close it.
