### ISSUE TITLE
Client Crash - 

### ISSUE THREAD

**Issue by ProsperCraft** [feldim2425/MoreOverlays#44]
When on a multiplayer server, teleported to another player with F7 spawn x overlays on, and the client crashed.

TownCraft Modpack 2.07

https://gist.github.com/ProsperCraft/c960a0de01928dcc8b43fb21a1adb83e

**Comment by feldim2425** [comment]
This seems to be a bug in IC2.

**Comment by ProsperCraft** [comment]
No longer having this issue, Ic2 must have fixed it.
