### ISSUE TITLE
Can't toggle light overlay on server (mod useless in multiplayer)

### ISSUE THREAD

**Issue by ExDomino** [feldim2425/MoreOverlays#45]
Minecraft: 1.12.2
Forge: 14.23.3.2669
JEI: 1.12.2-4.8.5.159
MoreOverlay: 1.13-mc1.12.1
Keybinds: F7 (not working on any key)
Mode: Multiplayer (mods installed on server as well, same versions)

Chunk boundaries is working but not light overlay. Work in singleplayer but not in multiplayer, except if you first open one of your singleplayer world since you open the game.

Workaround: go to singleplayer, toggle on light overlay and then go to multiplayer, you can now toggle light overlay as normal until you close and re-open the game.

**Comment by feldim2425** [comment]
Does the Light overlay (after you enabled it in singleplayer) work correctly in multiplayer?
EDIT: So if you turn it on in singleplayer and switch to multiplayer, does it update the light values correctly?

**Comment by feldim2425** [comment]
I don't have any problems in multiplayer. It seems like something blocks the KeyBinding. Have you tried changing the Key from F7 to another key?

**Comment by thecanidcoder** [comment]
My wife and I have run into the same issue; unfortunately, it's not terribly consistent and has thus been hard to track down. Changing the keybind worked for me a couple times, but then has not worked afterwards.

On my wife's PC and *specifically* in Twilight Forest, the X's will just flicker like crazy all over the place, while continuing to just plain not work in the Overworld.

**Comment by feldim2425** [comment]
Just to be sure... Do you have any Shaders enabled? They might mess with the line rendering a bit.
What Modpacks have this issue, or with what mods does it appear? I will at least try it with Twilight Forest.

**Comment by thecanidcoder** [comment]
I apologize; I missed the email for this thread.

I do not use shaders, Optifine nor any resource packs. My wife does use Optifine. This was originally appearing in the [Roguelike Adventures and Dungeons](https://minecraft.curseforge.com/projects/roguelike-adventures-and-dungeons) pack, and has continued happening in my own self-made mod set.

**Comment by ghost** [comment]
Oh good, it's not just me. I've been having roughly the same issue on my test pack, and I can't think of anything obvious that would break it. Chunk borders work flawlessly, but the lighting overlay is sporadic at best. Most of the time it doesn't work, but once in a while it will work for a little bit, but the markings on the ground will flicker like those annoying Christmas lights.

Edit: a pack tester has suggested that it may be related to a rendering setting in mekanism. I will give this a test this upcoming weekend.

Pack link: https://minecraft.curseforge.com/projects/continuity/files

**Comment by ZeShaKy** [comment]
Sorry to talk about this too late but I have tested and found that it was Mo' Creatures who created this issue for me. When I delete it, MoreOverlays works perfectly. I hope this will help !

**Comment by feldim2425** [comment]
Oh in this case the bug is probably related to Pull Request #57

**Comment by feldim2425** [comment]
I fixed this in commit 2a9878b34ad6d2bd1607475c568f7f977d62091b ... so this should hopefully be fixed in the next version
