### ISSUE TITLE
Highlight item is highlighting all items in inventory

### ISSUE THREAD

**Issue by superfluke** [feldim2425/MoreOverlays#46]
Having an issue where the highlight item function only sometimes works. Searching for 'comb' for example will highlight all items until the 'b' is typed, while a search for 'spider' highlights all items, not just the spider eye: 
![image](https://user-images.githubusercontent.com/20022336/39972488-34ff7158-56df-11e8-94fc-001e153af72e.png)

Looks like the same issue was reported on the JEI issue page as well: https://github.com/mezz/JustEnoughItems/issues/1195

jei_1.12.2-4.8.5.159.jar
moreoverlays-1.13-mc1.12.1

**Comment by Shovinus** [comment]
#49

**Comment by feldim2425** [comment]
Fixed in e188322
