### ISSUE TITLE
Light level overlay broken with MoCreatures installed (MC 1.12.2, Forge 2808)

### ISSUE THREAD

**Issue by xs2007** [feldim2425/MoreOverlays#58]
As the title says, the light level overlay does not work, when DrZharks MoCreatures is installed, or more specifically DrZharks CustomMobSpawner (that is a library for MoCreatures).

I wrote an integration patch and opened a pull request for it, in case you want to add it to the base mod.

**Comment by feldim2425** [comment]
Since the pull request is open ( #57 ) and I will look into adding some sort of custom spawner overrides to MoreOverlays, I will close this one for the moment.
