### ISSUE TITLE
Item Search does not support subtypes

### ISSUE THREAD

**Issue by justinrusso** [feldim2425/MoreOverlays#60]
### Context:
Using the item search, it fails to differentiate between items with different NBT.

In this case, I'm attempting to search for a "slime seed" but highlights 2 seeds in my inventory which are not slime seeds but use the same base item. For cases like this, the mod registers a JEI subtype interpreter to handle the item properly for recipe lookups.

![image](https://user-images.githubusercontent.com/25138621/56627915-cf503f80-6615-11e9-9a7c-05ec8ee6e9bf.png)

### Versions:
Minecraft: 1.12.2
Forge: 14.23.5.2831
More Overlays: 1.14
JEI: 4.15.0.278

**Comment by feldim2425** [comment]
Maybe I have to add a blacklist or some other way to find items that aren't differentiated via NBT by JEI.
The current behavior is sort of intentional since it is the only way to properly search enchanted books but I have to do some research here.
