### ISSUE TITLE
Double Clicking JEI search bar doesn't search inventory while in Creative

### ISSUE THREAD

**Issue by katubug** [feldim2425/MoreOverlays#63]
Hello! First off, thank you for this mod. It's incredibly useful and I've greatly enjoyed it.

However, it seems that recent JEI updates may have broken the function where you can double click on the search bar and it will search your inventory instead of JEI? I haven't ruled out user error, but for whatever reason, double clicking the JEI search bar is not working.

Here are my mod versions:
jei_1.12.2-4.15.0.280
moreoverlays-1.14-mc1.12.2

My full modlist with versions is at the bottom of this post: http://enthusiasticraft.cf/modpack-update-1-5-1/

**Comment by katubug** [comment]
Had someone else report it was working for them so I did a test: Apparently it works properly while in survival mode, but not in creative. I'm not sure if this is intended or not so I'm going to leave the issue open. If it is intended, please feel free to close this.

**Comment by feldim2425** [comment]
Currently this is intended. Since the UI somehow offsets the Search overlay for the items. I might look into this, since I already fixed the same bug for Mantle Mods (like Tinkers Construct). At that time this didn't seemed to be a very important feature for creative so I just disabled it.

**Comment by katubug** [comment]
I admit it's not a huge priority for me for it to work in creative as I
mostly use it in survival anyway. I was just thrown off by it suddenly
disappearing (or so I thought! Lol).

**Comment by feldim2425** [comment]
Ok. I changed some stuff on how my mod reads the gui offset a bit. So item search should work in creative inventories in the next version.
