### ISSUE TITLE
F7 Light level overlay doesn't work in multiplayer.

### ISSUE THREAD

**Issue by Joccob** [feldim2425/MoreOverlays#68]
Version:  moreoverlays-1.15.1

Issues: For some reason, F7 light overlay not showing in multiplayer but chunk boundary and search function has no issues. I tried to change the key bound but it still doesn't work. Also, everything works perfectly when I test with the same mods in single player.

**Comment by feldim2425** [comment]
Does it work if you go into the Mod Options ->  MoreOverlays -> Config -> Lightoverlay and set ignoreSpawns to true? If thats the case something messes up the spawn list

**Comment by Joccob** [comment]
Thank you for your help. It worked after I changed the setting. Maybe like you sad, some of the mods messed up the spawn list.
