### ISSUE TITLE
Darkened slots render over tooltips when item search is enabled

### ISSUE THREAD

**Issue by mezz** [feldim2425/MoreOverlays#7]
![2016-05-03_22 40 16](https://cloud.githubusercontent.com/assets/916092/15005974/330c2928-1180-11e6-92ed-31bd3d7a681e.png)

Minecraft 1.9, Forge 12.16.0.1867, moreoverlays-1.2-mc1.9
This happens even with JEI closed so it's probably not another mod's OpenGL issue.

**Comment by feldim2425** [comment]
I know, but I don't think that there is a render event after the gui is rendered and before rendering the tooltip.

**Comment by mezz** [comment]
Rendering the tooltip again is how I got around a similar issue in JEI too, before I added a new Forge event at the spot I wanted to render. I think this fix will work fine.

You should use the new `GuiUtils.drawHoveringText` method in Forge instead of your `GuiUtil` class though.

Thanks for the quick fixes!
