### ISSUE TITLE
"Item Search Enabled" and "Item Search Disabled" text never disappears

### ISSUE THREAD

**Issue by mezz** [feldim2425/MoreOverlays#9]
The text just stays there and never fades out, long after you toggle it on or off.
I think it would be best if it faded out like when you select an item on your hotbar.
If you didn't know the hotkey already, it's confusing to see that text.

**Comment by feldim2425** [comment]
Commit: 2e715ef
Text will fade out after a second (Can be disabled in the config. Default: true) 
[In the next version]
